spring:
  application:
    name: helpbot-agent
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: gpt-4o-mini
    mcp:
      client:
        streamable-http:
          connections:
            helpbot-mcp-server:
              url: http://localhost:8080
              endpoint: /mcp
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
server:
  port: 8081
